name: voo_navigation
packages:
  - packages/ui/*

command:
  bootstrap:
    environment:
      sdk: '>=3.8.1 <4.0.0'
      flutter: '>=3.0.0 <4.0.0'
    dependencies:
      flutter_bloc: ^9.1.1
      bloc: ^9.0.0
      equatable: ^2.0.5
      go_router: ^16.2.2
      meta: ^1.9.0
    dev_dependencies:
      build_runner: ^2.4.0
      bloc_test: ^10.0.0
      flutter_lints: ^6.0.0

  version:
    workspaceChangelog: true
    branch: main
    updateGitTagRefs: true
    message: |
      chore(release): publish packages

      {new_package_versions}

scripts:
  get:
    description: Get dependencies for all packages.
    run: melos bootstrap

  clean:
    description: Clean all packages.
    run: melos clean

  test_all:
    description: Run tests for all packages.
    run: melos run test --no-select

  test:
    description: Run tests for selected packages.
    run: melos exec -- flutter test

  analyze:
    description: Run analyzer for all packages.
    run: melos exec -- flutter analyze

  format:
    description: Format all packages.
    run: dart format .

  format_check:
    description: Check formatting for all packages.
    run: dart format --set-exit-if-changed .

  nuke_stale_state:
    description: Nuke stale state from all packages.
    run: melos exec -- bash -c 'rm -rf pubspec.lock .dart_tool build'
