include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Allow importing from lib/src of voo_navigation_core (same ecosystem)
    implementation_imports: false
    unnecessary_library_name: false
